hostname: appbox
domain: local
ip: 192.168.56.105

project:
    dir: project

db:
    host: 127.0.0.1
    port: 3306
    name: gdb_sso
    username: appuser
    password: m0n1c4po
    root_password: m0n1c4po
